version: '1'

# 系统配置
application:
  env: debug  # 合法选项 "" (默认为空 = debug ) "debug" "release" "test"
  host: 0.0.0.0
  port: 8088
  public_path:
  domain: "" # 设置 set-cookie httpOnly=true 使用，能有效防止 csrf 攻击

# 数据库配置
mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  pwd: gs963852
  db: j2pay
  prefix:
  max_idle: 30
  max_active: 15

# 日志配置
log:
  path:
  level: info # 合法选项 "panic" "fatal" "error" "warn" "warning" "info" "debug" "trace"

# rbac 权限配置
casbin:
  path:

# 验证码配置
captcha:
  length: 4
  width: 150
  height: 50
#  str: 234567890abcdefghjkmnpqrstuvwxyz
  str: 1234567890abcdefghjkmnpqrstuvwxyz
  font:
    - wqy-microhei.ttc
  noise: 100
  line: 3

# json web token 配置
jwt:
  key: bfgdiojhnpbwfsfa23/*-/*-/sgdeasdg4sd6+0@%!
  exp_time: 100 #小时

# eth 配置
eth:
# url: http://127.0.0.1:8545 #本地网络
# url: https://mainnet.infura.io/v3/fca54f064a584d378cfedff40eabeef5 #以太坊主网络
  url: https://ropsten.infura.io/v3/fca54f064a584d378cfedff40eabeef5 #ropsten测试网络
  cold_wallet_address: #eth冷钱包地址
  erc20_cold_wallet_address: #erc20冷钱包地址

# AES key
aes:
  key: j2pay

# AppSignExpiry
sign:
  app_sign_expiry: 120
