// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/adminUser": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户管理"
                ],
                "summary": "获取账户列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "默认0：查商户列表，1:查商户账户列表",
                        "name": "Pid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AdminUserPage"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户管理"
                ],
                "summary": "添加账户",
                "parameters": [
                    {
                        "description": "用户",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserAdd"
                        }
                    }
                ]
            }
        },
        "/adminUser/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户管理"
                ],
                "summary": "获取账户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AdminUserList"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户管理"
                ],
                "summary": "编辑账户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserEdit"
                        }
                    }
                ]
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户管理"
                ],
                "summary": "删除账户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/auth/role": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "账户管理"
                ],
                "summary": "获取角色树",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AdminUserPage"
                        }
                    }
                }
            }
        },
        "/auth/tree": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "获取权限树",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RolePage"
                        }
                    }
                }
            }
        },
        "/captcha": {
            "get": {
                "tags": [
                    "登录操作"
                ],
                "summary": "验证码",
                "responses": {
                    "200": {}
                }
            }
        },
        "/detail": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "实收明细记录"
                ],
                "summary": "实收明细记录列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "状态 1：未绑定，2：已绑定",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "系统编号",
                        "name": "idCode",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "商户id",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "交易hash",
                        "name": "txid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "收款地址",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "至",
                        "name": "to_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DetailedRecordPage"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "实收明细记录"
                ],
                "summary": "新增实收明细记录",
                "parameters": [
                    {
                        "description": "实收记录",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DetailedAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/detail/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "实收明细记录"
                ],
                "summary": "实收记录详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.DetailedList"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "实收明细记录"
                ],
                "summary": "绑定 | 解绑 订单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "明细记录",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.DetailedEdit"
                        }
                    }
                ]
            }
        },
        "/fee": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "手续费结账"
                ],
                "summary": "手续费列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "状态 1：等待中，2：已完成",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "商户id",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "至",
                        "name": "to_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.FeePage"
                        }
                    }
                }
            }
        },
        "/fee/{id}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "手续费结账"
                ],
                "summary": "结账",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "手续费",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FeeEdit"
                        }
                    }
                ]
            }
        },
        "/index": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员首页"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SystemMessagePage"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "登录操作"
                ],
                "summary": "登录操作",
                "parameters": [
                    {
                        "description": "用户",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.LoginUser"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/merchantPick": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "商户提领、代发列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "-1：等待中，1:执行中，2：成功，3：取消，4，失败",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "0：所有，1：代发，2：提领",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商户订单编号",
                        "name": "orderCode",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "商户id",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "至",
                        "name": "to_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MerchantPickSendPage"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "提领",
                "parameters": [
                    {
                        "description": "商户提领",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.PickAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/merchantPick/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "商户提领代发详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.MerchantPickList"
                        }
                    }
                }
            }
        },
        "/merchantSend": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "提领",
                "parameters": [
                    {
                        "description": "商户代发",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/notify": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "通知",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {}
                }
            }
        },
        "/order": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单管理"
                ],
                "summary": "订单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "状态 -1：收款中，1：已完成，2：异常，3：退款等待中，4：退款中，5：退款失败，6：已退款，7：已过期",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商户订单编号",
                        "name": "orderCode",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "商户id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "交易哈希",
                        "name": "txid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "收款地址",
                        "name": "chargeAddress",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "至",
                        "name": "to_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.OrderPage"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单管理"
                ],
                "summary": "新增订单",
                "parameters": [
                    {
                        "description": "新增订单",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.OrderAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/order/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "订单管理"
                ],
                "summary": "订单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Order"
                        }
                    }
                }
            }
        },
        "/pick": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "管理端商户提领列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "-1：等待中，1:执行中，2：成功，3：取消，4，失败",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "0：所有，1：代发，2：提领",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "商户id",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "至",
                        "name": "to_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PickUpPage"
                        }
                    }
                }
            }
        },
        "/pick/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "管理端商户提领详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PickList"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "修改提领订单状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "提领订单",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.SendEdit"
                        }
                    }
                ]
            }
        },
        "/return": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "退款订单管理"
                ],
                "summary": "退款订单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "状态 1：退款等待中，2：退款中，3：退款失败，4：已退款",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商户订单编号",
                        "name": "orderCode",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "至",
                        "name": "to_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ReturnPage"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "退款订单管理"
                ],
                "summary": "新增退款订单",
                "parameters": [
                    {
                        "description": "新增退款订单",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ReturnAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/return/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "退款订单管理"
                ],
                "summary": "退款订单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Return"
                        }
                    }
                }
            }
        },
        "/role": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "获取所有角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RolePage"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "添加角色",
                "parameters": [
                    {
                        "description": "角色",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RoleAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/role/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "获取角色详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RoleList"
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "编辑角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "角色",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.RoleEdit"
                        }
                    }
                ]
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色管理"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/send": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "管理端商户代发列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "-1：等待中，1:执行中，2：成功，3：取消，4，失败",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "0：所有，1：代发，2：提领",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商户订单编号",
                        "name": "orderCode",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "商户id",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起",
                        "name": "from_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "至",
                        "name": "to_date",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SendPage"
                        }
                    }
                }
            }
        },
        "/send/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户提领代发管理"
                ],
                "summary": "管理端商户代发详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SendList"
                        }
                    }
                }
            }
        },
        "/systemMessage": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统公告"
                ],
                "summary": "获取系统公告列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.SystemMessagePage"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统公告"
                ],
                "summary": "添加系统公告",
                "parameters": [
                    {
                        "description": "系统公告",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.MessageAdd"
                        }
                    }
                ],
                "responses": {
                    "200": {}
                }
            }
        },
        "/systemMessage/{id}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统公告"
                ],
                "summary": "编辑公告",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "公告",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.MessageEdit"
                        }
                    }
                ]
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统公告"
                ],
                "summary": "删除公告",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "公告ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ]
            }
        },
        "/systemMessageByUser": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统公告"
                ],
                "summary": "获取用户公告列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页显示多少条",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.AdminUserMessagePage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AdminUser": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "createTime": {
                    "type": "string"
                },
                "daiCharge": {
                    "type": "number"
                },
                "daiType": {
                    "type": "integer"
                },
                "daiUrl": {
                    "type": "string"
                },
                "dayTotalCount": {
                    "type": "number"
                },
                "examine": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "isCollection": {
                    "type": "integer"
                },
                "isCreation": {
                    "type": "integer"
                },
                "isDai": {
                    "type": "integer"
                },
                "isGas": {
                    "type": "integer"
                },
                "isOpen": {
                    "type": "integer"
                },
                "lastLoginTime": {
                    "type": "string"
                },
                "limit": {
                    "type": "number"
                },
                "maxOrderCount": {
                    "type": "number"
                },
                "minOrderCount": {
                    "type": "number"
                },
                "more": {
                    "type": "integer"
                },
                "orderCharge": {
                    "type": "number"
                },
                "orderType": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "pick": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Pick"
                    }
                },
                "pid": {
                    "type": "integer"
                },
                "qrcodeUrl": {
                    "type": "string"
                },
                "realName": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "returnCharge": {
                    "type": "number"
                },
                "returnType": {
                    "type": "integer"
                },
                "returnUrl": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "systemMessages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SystemMessage"
                    }
                },
                "tel": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "updateTime": {
                    "type": "string"
                },
                "userLessTime": {
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "model.Order": {
            "type": "object",
            "properties": {
                "admin_user": {
                    "description": "指定关联外键",
                    "type": "object",
                    "$ref": "#/definitions/model.AdminUser"
                },
                "amount": {
                    "type": "number"
                },
                "chargeAddress": {
                    "type": "string"
                },
                "fee": {
                    "type": "number"
                },
                "finishTime": {
                    "type": "string"
                },
                "merchantAmount": {
                    "type": "number"
                },
                "order_code": {
                    "type": "string"
                },
                "receiptAmount": {
                    "type": "number"
                },
                "remark": {
                    "type": "string"
                },
                "returnAmount": {
                    "type": "number"
                },
                "status": {
                    "type": "integer"
                },
                "txid": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "model.OrderPage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Order"
                    }
                },
                "merchant_amount": {
                    "description": "总商户总实收金额",
                    "type": "number"
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "really_amount": {
                    "description": "总实收金额",
                    "type": "number"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                },
                "total_amount": {
                    "description": "总订单金额",
                    "type": "number"
                },
                "total_fee": {
                    "description": "总手续费",
                    "type": "number"
                }
            }
        },
        "model.Pick": {
            "type": "object",
            "properties": {
                "admin_user": {
                    "description": "指定关联外键",
                    "type": "object",
                    "$ref": "#/definitions/model.AdminUser"
                },
                "amount": {
                    "type": "number"
                },
                "fee": {
                    "type": "number"
                },
                "finishTime": {
                    "type": "string"
                },
                "idCode": {
                    "type": "string"
                },
                "order_code": {
                    "type": "string"
                },
                "pickAddress": {
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "txid": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "model.Return": {
            "type": "object",
            "properties": {
                "admin_user": {
                    "description": "指定关联外键",
                    "type": "object",
                    "$ref": "#/definitions/model.AdminUser"
                },
                "amount": {
                    "type": "number"
                },
                "finishTime": {
                    "type": "string"
                },
                "order_code": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "system_code": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "model.ReturnPage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Return"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "model.SystemMessage": {
            "type": "object",
            "properties": {
                "adminUsers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AdminUser"
                    }
                },
                "beginTime": {
                    "type": "string"
                },
                "endTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "request.DetailedAdd": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "金额",
                    "type": "number"
                },
                "charge_address": {
                    "description": "收款地址",
                    "type": "string"
                },
                "create_at": {
                    "description": "时间",
                    "type": "string"
                },
                "from_address": {
                    "description": "发款地址",
                    "type": "string"
                },
                "id_code": {
                    "description": "系统编号",
                    "type": "string"
                },
                "txid": {
                    "description": "交易hash",
                    "type": "string"
                }
            }
        },
        "request.DetailedEdit": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "is_bind": {
                    "description": "1：解绑 2：绑定",
                    "type": "integer"
                },
                "order_code": {
                    "description": "商户订单编号",
                    "type": "string"
                }
            }
        },
        "request.FeeEdit": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "status": {
                    "description": "状态 1：执行中 2：已完成",
                    "type": "integer"
                }
            }
        },
        "request.LoginUser": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "google_code": {
                    "description": "google 动态验证码",
                    "type": "string",
                    "example": "952721"
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "admin"
                },
                "username": {
                    "description": "用户名",
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "request.MessageAdd": {
            "type": "object",
            "required": [
                "beginTime",
                "endTime",
                "title",
                "users"
            ],
            "properties": {
                "beginTime": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2020-09-15T14:41:46+08:00"
                },
                "endTime": {
                    "description": "结束时间",
                    "type": "string",
                    "example": "2020-09-23T14:41:50+08:00"
                },
                "title": {
                    "description": "系统公告",
                    "type": "string",
                    "example": "这是一个系统公告"
                },
                "users": {
                    "description": "发给用户id",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7
                    ]
                }
            }
        },
        "request.MessageEdit": {
            "type": "object",
            "required": [
                "beginTime",
                "endTime",
                "title",
                "users"
            ],
            "properties": {
                "beginTime": {
                    "description": "开始时间",
                    "type": "string",
                    "example": "2020-09-15T14:41:46+08:00"
                },
                "endTime": {
                    "description": "结束时间",
                    "type": "string",
                    "example": "2020-09-23T14:41:50+08:00"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "description": "系统公告",
                    "type": "string",
                    "example": "这是一个系统公告"
                },
                "users": {
                    "description": "发给用户id",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7
                    ]
                }
            }
        },
        "request.OrderAdd": {
            "type": "object",
            "required": [
                "amount",
                "orderCode",
                "remark",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "description": "数量",
                    "type": "number",
                    "example": 1
                },
                "orderCode": {
                    "description": "商户订单编号",
                    "type": "string",
                    "example": "asfasgdsasfgas"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "example": "备注"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "request.PickAdd": {
            "type": "object",
            "required": [
                "amount",
                "pick_address",
                "remark",
                "type",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "description": "数量",
                    "type": "number",
                    "example": 1
                },
                "pick_address": {
                    "description": "收款地址",
                    "type": "string",
                    "example": "0x1243cfsadfcsd"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "example": "备注"
                },
                "type": {
                    "description": "类型 1：代发 0：提领",
                    "type": "integer",
                    "example": 1
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "request.ReturnAdd": {
            "type": "object",
            "required": [
                "amount",
                "orderCode",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "description": "实收金额金额",
                    "type": "number",
                    "example": 1
                },
                "orderCode": {
                    "description": "商户订单编号",
                    "type": "string",
                    "example": "asfasgdsasfgas"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "request.RoleAdd": {
            "type": "object",
            "required": [
                "auth",
                "name"
            ],
            "properties": {
                "auth": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19
                    ]
                },
                "name": {
                    "description": "角色名",
                    "type": "string",
                    "example": "程序员"
                },
                "pid": {
                    "description": "上级ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "request.RoleEdit": {
            "type": "object",
            "required": [
                "auth",
                "name"
            ],
            "properties": {
                "auth": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19
                    ]
                },
                "name": {
                    "description": "角色名",
                    "type": "string",
                    "example": "程序员"
                },
                "pid": {
                    "description": "上级ID",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "request.SendAdd": {
            "type": "object",
            "required": [
                "amount",
                "order_code",
                "pick_address",
                "remark",
                "type",
                "user_id"
            ],
            "properties": {
                "amount": {
                    "description": "数量",
                    "type": "number",
                    "example": 1
                },
                "order_code": {
                    "description": "商户订单编号",
                    "type": "string",
                    "example": "asfasgdsasfgas"
                },
                "pick_address": {
                    "description": "收款地址",
                    "type": "string",
                    "example": "0x1243cfsadfcsd"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "example": "备注"
                },
                "type": {
                    "description": "类型 1：代发 0：提领",
                    "type": "integer",
                    "example": 1
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "request.SendEdit": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "description": "状态 0：等待中，1：执行中，2：成功，3：已取消，4：失败",
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "request.UserAdd": {
            "type": "object",
            "required": [
                "address",
                "dai_charge",
                "dai_url",
                "day_total_count",
                "examine",
                "limit",
                "max_order_count",
                "min_order_count",
                "more",
                "order_charge",
                "password",
                "pid",
                "real_name",
                "remark",
                "return_charge",
                "return_url",
                "roles",
                "tel",
                "user_less_time",
                "user_name"
            ],
            "properties": {
                "address": {
                    "description": "商户地址",
                    "type": "string",
                    "example": "test"
                },
                "dai_charge": {
                    "description": "代发手续费",
                    "type": "number",
                    "example": 1
                },
                "dai_type": {
                    "description": "代发手续费类型 1：百分比 0：固定",
                    "type": "integer",
                    "example": 1
                },
                "dai_url": {
                    "description": "代发URL",
                    "type": "string",
                    "example": "test"
                },
                "day_total_count": {
                    "description": "每日交易总量",
                    "type": "number",
                    "example": 1
                },
                "examine": {
                    "description": "代发审核",
                    "type": "number",
                    "example": 1
                },
                "is_collection": {
                    "description": "是否开启收款功能 1：是 0：否",
                    "type": "integer",
                    "example": 1
                },
                "is_creation": {
                    "description": "是否开启手动建单 1：是 0：否",
                    "type": "integer",
                    "example": 1
                },
                "is_dai": {
                    "description": "是否启用代发功能",
                    "type": "integer",
                    "example": 1
                },
                "is_gas": {
                    "description": "是否启用gas预估 1：是 0：否",
                    "type": "integer",
                    "example": 1
                },
                "limit": {
                    "description": "结账限制",
                    "type": "number",
                    "example": 1
                },
                "max_order_count": {
                    "description": "最大交易总量",
                    "type": "number",
                    "example": 1
                },
                "min_order_count": {
                    "description": "最小交易总量",
                    "type": "number",
                    "example": 1
                },
                "more": {
                    "description": "地址多单收款",
                    "type": "integer",
                    "example": 1
                },
                "order_charge": {
                    "description": "订单手续费",
                    "type": "number",
                    "example": 1
                },
                "order_type": {
                    "description": "订单手续费类型 1：百分比 0：固定",
                    "type": "integer",
                    "example": 1
                },
                "password": {
                    "description": "密码",
                    "type": "string",
                    "example": "test"
                },
                "pid": {
                    "description": "所属组织ID",
                    "type": "integer",
                    "example": 1
                },
                "real_name": {
                    "description": "组织名称",
                    "type": "string",
                    "example": "test"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "example": "test"
                },
                "return_charge": {
                    "description": "退款手续费",
                    "type": "number",
                    "example": 1
                },
                "return_type": {
                    "description": "退款手续费类型 1：百分比 0：固定",
                    "type": "integer",
                    "example": 1
                },
                "return_url": {
                    "description": "回传URL",
                    "type": "string",
                    "example": "test"
                },
                "roles": {
                    "description": "所属角色",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "status": {
                    "description": "状态 1：正常 0：禁用",
                    "type": "integer",
                    "example": 1
                },
                "tel": {
                    "description": "电话号码",
                    "type": "string",
                    "example": "17585534067"
                },
                "user_less_time": {
                    "description": "订单无效时间",
                    "type": "integer",
                    "example": 1
                },
                "user_name": {
                    "description": "账号",
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "request.UserEdit": {
            "type": "object",
            "required": [
                "address",
                "dai_charge",
                "dai_url",
                "day_total_count",
                "examine",
                "limit",
                "max_order_count",
                "min_order_count",
                "more",
                "order_charge",
                "pid",
                "real_name",
                "remark",
                "return_charge",
                "return_url",
                "roles",
                "tel",
                "user_less_time",
                "user_name"
            ],
            "properties": {
                "address": {
                    "description": "商户地址",
                    "type": "string",
                    "example": "test"
                },
                "code": {
                    "description": "动态码",
                    "type": "string"
                },
                "dai_charge": {
                    "description": "代发手续费",
                    "type": "number",
                    "example": 1
                },
                "dai_type": {
                    "description": "代发手续费类型 1：百分比 0：固定",
                    "type": "integer",
                    "example": 1
                },
                "dai_url": {
                    "description": "代发URL",
                    "type": "string",
                    "example": "test"
                },
                "day_total_count": {
                    "description": "每日交易总量",
                    "type": "number",
                    "example": 1
                },
                "examine": {
                    "description": "代发审核",
                    "type": "number",
                    "example": 1
                },
                "is_collection": {
                    "description": "是否开启收款功能 1：是 0：否",
                    "type": "integer",
                    "example": 1
                },
                "is_creation": {
                    "description": "是否开启手动建单 1：是 0：否",
                    "type": "integer",
                    "example": 1
                },
                "is_dai": {
                    "description": "是否启用代发功能",
                    "type": "integer",
                    "example": 1
                },
                "is_gas": {
                    "description": "是否启用gas预估 1：是 0：否",
                    "type": "integer",
                    "example": 1
                },
                "is_open": {
                    "description": "是否开启双重验证 0：关闭 1：开启",
                    "type": "integer"
                },
                "limit": {
                    "description": "结账限制",
                    "type": "number",
                    "example": 1
                },
                "max_order_count": {
                    "description": "最大交易总量",
                    "type": "number",
                    "example": 1
                },
                "min_order_count": {
                    "description": "最小交易总量",
                    "type": "number",
                    "example": 1
                },
                "more": {
                    "description": "地址多单收款",
                    "type": "integer",
                    "example": 1
                },
                "order_charge": {
                    "description": "订单手续费",
                    "type": "number",
                    "example": 1
                },
                "order_type": {
                    "description": "订单手续费类型 1：百分比 0：固定",
                    "type": "integer",
                    "example": 1
                },
                "password": {
                    "description": "密码（非必填）",
                    "type": "string",
                    "example": "test"
                },
                "pid": {
                    "description": "所属组织ID",
                    "type": "integer",
                    "example": 1
                },
                "real_name": {
                    "description": "组织名称",
                    "type": "string",
                    "example": "test"
                },
                "remark": {
                    "description": "备注",
                    "type": "string",
                    "example": "test"
                },
                "return_charge": {
                    "description": "退款手续费",
                    "type": "number",
                    "example": 1
                },
                "return_type": {
                    "description": "退款手续费类型 1：百分比 0：固定",
                    "type": "integer",
                    "example": 1
                },
                "return_url": {
                    "description": "回传URL",
                    "type": "string",
                    "example": "test"
                },
                "roles": {
                    "description": "所属角色",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "status": {
                    "description": "状态 1：正常 0：禁用",
                    "type": "integer",
                    "example": 1
                },
                "tel": {
                    "description": "电话号码",
                    "type": "string",
                    "example": "17585534067"
                },
                "user_less_time": {
                    "description": "订单无效时间",
                    "type": "integer",
                    "example": 1
                },
                "user_name": {
                    "description": "账号",
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "response.AdminSystemMessage": {
            "type": "object",
            "properties": {
                "begin_time": {
                    "description": "开始时间",
                    "type": "string"
                },
                "end_time": {
                    "description": "结束时间",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                }
            }
        },
        "response.AdminUserList": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "商户地址",
                    "type": "string"
                },
                "balance": {
                    "description": "账户余额",
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "last_login_time": {
                    "description": "最后登录时间",
                    "type": "string"
                },
                "order_charge": {
                    "description": "提领fee",
                    "type": "number"
                },
                "qr_code_url": {
                    "description": "google 二维码地址",
                    "type": "string"
                },
                "real_name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "return_charge": {
                    "description": "退款fee",
                    "type": "number"
                },
                "roles": {
                    "description": "角色信息",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CasRole"
                    }
                },
                "secret": {
                    "description": "google密钥",
                    "type": "string"
                },
                "status": {
                    "description": "用户状态",
                    "type": "integer"
                },
                "tel": {
                    "description": "手机号码",
                    "type": "string"
                },
                "user_name": {
                    "description": "登录名",
                    "type": "string"
                }
            }
        },
        "response.AdminUserMessageList": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "systemMessages": {
                    "description": "系统公告",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AdminSystemMessage"
                    }
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "response.AdminUserMessagePage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AdminUserMessageList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "response.AdminUserPage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.AdminUserList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "response.CasRole": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "角色ID",
                    "type": "integer"
                },
                "name": {
                    "description": "角色名",
                    "type": "string"
                }
            }
        },
        "response.DetailedList": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "金额",
                    "type": "number"
                },
                "charge_address": {
                    "description": "收款地址",
                    "type": "string"
                },
                "create_at": {
                    "description": "时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "id_code": {
                    "description": "系统编号",
                    "type": "string"
                },
                "order_code": {
                    "description": "订单编号",
                    "type": "string"
                },
                "order_id": {
                    "description": "商户订单id",
                    "type": "integer"
                },
                "real_name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "status": {
                    "description": "状态 1：未绑定 2：已绑定",
                    "type": "integer"
                },
                "txid": {
                    "description": "交易hash",
                    "type": "string"
                },
                "user_id": {
                    "description": "商户id",
                    "type": "integer"
                }
            }
        },
        "response.DetailedRecordPage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.DetailedList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "response.FeeList": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "金额",
                    "type": "number"
                },
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "finish_time": {
                    "description": "完成时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "real_name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "status": {
                    "description": "状态 1：执行中 2：已完成",
                    "type": "integer"
                }
            }
        },
        "response.FeePage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.FeeList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "response.MerchantPickList": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "金额",
                    "type": "number"
                },
                "create_at": {
                    "description": "建立时间",
                    "type": "string"
                },
                "del_money": {
                    "description": "扣除商户余额",
                    "type": "number"
                },
                "fee": {
                    "description": "手续费",
                    "type": "number"
                },
                "finish_time": {
                    "description": "完成时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "id_code": {
                    "description": "系统编号",
                    "type": "string"
                },
                "order_code": {
                    "description": "商户订单编号",
                    "type": "string"
                },
                "real_name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "send_address": {
                    "description": "代发地址",
                    "type": "string"
                },
                "status": {
                    "description": "状态 0：等待中，1：执行中，2：成功，3：已取消，4：失败",
                    "type": "integer"
                },
                "txid": {
                    "description": "交易hash",
                    "type": "string"
                },
                "type": {
                    "description": "类型 1：提领，2：代发",
                    "type": "integer"
                },
                "user_id": {
                    "description": "商户id",
                    "type": "integer"
                }
            }
        },
        "response.MerchantPickSendPage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.MerchantPickList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                },
                "total_amount": {
                    "description": "提领总额",
                    "type": "number"
                },
                "total_fee": {
                    "description": "总手续费",
                    "type": "number"
                },
                "total_reduce": {
                    "description": "总减少金额",
                    "type": "number"
                }
            }
        },
        "response.PickList": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "金额",
                    "type": "number"
                },
                "create_at": {
                    "description": "建立时间",
                    "type": "string"
                },
                "finish_time": {
                    "description": "完成时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "id_code": {
                    "description": "系统编号",
                    "type": "string"
                },
                "real_name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "send_address": {
                    "description": "代发地址",
                    "type": "string"
                },
                "status": {
                    "description": "状态 0：等待中，1：执行中，2：成功，3：已取消，4：失败",
                    "type": "integer"
                },
                "txid": {
                    "description": "交易hash",
                    "type": "string"
                },
                "type": {
                    "description": "类型 1：提领，2：代发",
                    "type": "integer"
                },
                "user_id": {
                    "description": "商户id",
                    "type": "integer"
                }
            }
        },
        "response.PickUpPage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.PickList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "response.RoleList": {
            "type": "object",
            "properties": {
                "auth": {
                    "description": "所有权限arr",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "base_auth": {
                    "description": "api权限",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "角色名",
                    "type": "string"
                },
                "parent_name": {
                    "description": "上级角色名",
                    "type": "string"
                },
                "pid": {
                    "description": "上级ID",
                    "type": "integer"
                }
            }
        },
        "response.RolePage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.RoleList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "response.SendList": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "金额",
                    "type": "number"
                },
                "create_at": {
                    "description": "建立时间",
                    "type": "string"
                },
                "del_money": {
                    "description": "扣除商户余额",
                    "type": "number"
                },
                "fee": {
                    "description": "手续费",
                    "type": "number"
                },
                "finish_time": {
                    "description": "完成时间",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "integer"
                },
                "id_code": {
                    "description": "系统编号",
                    "type": "string"
                },
                "order_code": {
                    "description": "商户订单编号",
                    "type": "string"
                },
                "real_name": {
                    "description": "组织名称",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "send_address": {
                    "description": "代发地址",
                    "type": "string"
                },
                "status": {
                    "description": "状态 0：等待中，1：执行中，2：成功，3：已取消，4：失败",
                    "type": "integer"
                },
                "txid": {
                    "description": "交易hash",
                    "type": "string"
                },
                "type": {
                    "description": "类型 1：提领，2：代发",
                    "type": "integer"
                },
                "user_id": {
                    "description": "商户id",
                    "type": "integer"
                }
            }
        },
        "response.SendPage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SendList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "response.SystemMessageList": {
            "type": "object",
            "properties": {
                "begin_time": {
                    "description": "开始时间",
                    "type": "string"
                },
                "end_time": {
                    "description": "结束时间",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "status": {
                    "description": "是否作废 0：否，1：是",
                    "type": "integer"
                },
                "title": {
                    "description": "标题",
                    "type": "string"
                },
                "users": {
                    "description": "用户名称",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.UserNames"
                    }
                }
            }
        },
        "response.SystemMessagePage": {
            "type": "object",
            "properties": {
                "current_page": {
                    "description": "每页显示多少条",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.SystemMessageList"
                    }
                },
                "per_page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "total": {
                    "description": "总共多少页",
                    "type": "integer"
                }
            }
        },
        "response.UserNames": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "user_name": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "y2pay",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
