definitions:
  request.LoginUser:
    properties:
      password:
        description: 密码
        example: admin
        type: string
      username:
        description: 用户名
        example: admin
        type: string
      verify_code:
        description: 验证码
        example: "9527"
        type: string
    required:
    - password
    - username
    - verify_code
    type: object
  request.MessageAdd:
    properties:
      beginTime:
        description: 开始时间
        example: "2020-09-15T14:41:46+08:00"
        type: string
      endTime:
        description: 结束时间
        example: "2020-09-23T14:41:50+08:00"
        type: string
      title:
        description: 系统公告
        example: 这是一个系统公告
        type: string
      users:
        description: 发给用户id
        example:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        items:
          type: integer
        type: array
    required:
    - beginTime
    - endTime
    - title
    - users
    type: object
  request.MessageEdit:
    properties:
      beginTime:
        description: 开始时间
        example: "2020-09-15T14:41:46+08:00"
        type: string
      endTime:
        description: 结束时间
        example: "2020-09-23T14:41:50+08:00"
        type: string
      title:
        description: 系统公告
        example: 这是一个系统公告
        type: string
      users:
        description: 发给用户id
        example:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        items:
          type: integer
        type: array
    required:
    - beginTime
    - endTime
    - title
    - users
    type: object
  request.RoleAdd:
    properties:
      auth:
        example:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        items:
          type: integer
        type: array
      name:
        description: 角色名
        example: 程序员
        type: string
      pid:
        description: 上级ID
        example: 1
        type: integer
    required:
    - auth
    - name
    type: object
  request.RoleEdit:
    properties:
      auth:
        example:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        items:
          type: integer
        type: array
      name:
        description: 角色名
        example: 程序员
        type: string
      pid:
        description: 上级ID
        example: 1
        type: integer
    required:
    - auth
    - name
    type: object
  request.UserAdd:
    properties:
      password:
        description: 密码
        example: test
        type: string
      real_name:
        description: 真实姓名
        example: test
        type: string
      roles:
        description: 所属角色
        example:
        - 1
        - 2
        items:
          type: integer
        type: array
      status:
        description: 状态
        example: 1
        type: integer
      tel:
        description: 电话号码
        example: "17585534067"
        type: string
      user_name:
        description: 账号
        example: test
        type: string
    required:
    - password
    - real_name
    - roles
    - tel
    - user_name
    type: object
  request.UserEdit:
    properties:
      password:
        description: 密码（非必填）
        example: test
        type: string
      real_name:
        description: 真实姓名
        example: test
        type: string
      roles:
        description: 所属角色
        example:
        - 1
        - 2
        items:
          type: integer
        type: array
      status:
        description: 状态
        example: 1
        type: integer
      tel:
        description: 电话号码
        example: "17585534067"
        type: string
      user_name:
        description: 账号
        example: test
        type: string
    required:
    - real_name
    - roles
    - tel
    - user_name
    type: object
  response.AdminUserList:
    properties:
      id:
        type: integer
      real_name:
        description: 真实姓名
        type: string
      roles:
        description: 角色信息
        items:
          $ref: '#/definitions/response.CasRole'
        type: array
      status:
        description: 用户状态
        type: integer
      tel:
        description: 手机号码
        type: string
      user_name:
        description: 登录名
        type: string
    type: object
  response.AdminUserPage:
    properties:
      current_page:
        description: 每页显示多少条
        type: integer
      data:
        items:
          $ref: '#/definitions/response.AdminUserList'
        type: array
      per_page:
        description: 当前页码
        type: integer
      total:
        description: 总共多少页
        type: integer
    type: object
  response.CasRole:
    properties:
      id:
        description: 角色ID
        type: integer
      name:
        description: 角色名
        type: string
    type: object
  response.RoleList:
    properties:
      auth:
        description: 所有权限arr
        items:
          type: integer
        type: array
      base_auth:
        description: api权限
        items:
          type: integer
        type: array
      id:
        type: integer
      name:
        description: 角色名
        type: string
      parent_name:
        description: 上级角色名
        type: string
      pid:
        description: 上级ID
        type: integer
    type: object
  response.RolePage:
    properties:
      current_page:
        description: 每页显示多少条
        type: integer
      data:
        items:
          $ref: '#/definitions/response.RoleList'
        type: array
      per_page:
        description: 当前页码
        type: integer
      total:
        description: 总共多少页
        type: integer
    type: object
  response.SystemMessageList:
    properties:
      begin_time:
        description: 开始时间
        type: string
      end_time:
        description: 结束时间
        type: string
      id:
        description: id
        type: integer
      status:
        description: 是否作废 0：否，1：是
        type: integer
      title:
        description: 标题
        type: string
      users:
        description: 用户名称
        items:
          $ref: '#/definitions/response.UserNames'
        type: array
    type: object
  response.SystemMessagePage:
    properties:
      current_page:
        description: 每页显示多少条
        type: integer
      data:
        items:
          $ref: '#/definitions/response.SystemMessageList'
        type: array
      per_page:
        description: 当前页码
        type: integer
      total:
        description: 总共多少页
        type: integer
    type: object
  response.UserNames:
    properties:
      id:
        description: 用户ID
        type: integer
      user_name:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: y2pay
paths:
  /adminUser:
    get:
      parameters:
      - description: 姓名|手机
        in: query
        name: name
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页显示多少条
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AdminUserPage'
      summary: 获取账户列表
      tags:
      - 账户管理
    post:
      parameters:
      - description: 用户
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UserAdd'
      produces:
      - application/json
      summary: 添加账户
      tags:
      - 账户管理
  /adminUser/{id}:
    delete:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: 删除账户
      tags:
      - 账户管理
    get:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AdminUserList'
      summary: 获取账户详情
      tags:
      - 账户管理
    put:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 用户
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.UserEdit'
      produces:
      - application/json
      summary: 编辑账户
      tags:
      - 账户管理
  /auth/role:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.AdminUserPage'
      summary: 获取角色树
      tags:
      - 账户管理
  /auth/tree:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RolePage'
      summary: 获取权限树
      tags:
      - 角色管理
  /captcha:
    get:
      responses:
        "200": {}
      summary: 验证码
      tags:
      - 登录操作
  /index:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SystemMessagePage'
      tags:
      - 管理员首页
  /login:
    post:
      parameters:
      - description: 用户
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.LoginUser'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 登录操作
      tags:
      - 登录操作
  /role:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页显示多少条
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RolePage'
      summary: 获取所有角色
      tags:
      - 角色管理
    post:
      parameters:
      - description: 角色
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.RoleAdd'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 添加角色
      tags:
      - 角色管理
  /role/{id}:
    delete:
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: 删除角色
      tags:
      - 角色管理
    get:
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.RoleList'
      summary: 获取角色详情
      tags:
      - 角色管理
    put:
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      - description: 角色
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.RoleEdit'
      produces:
      - application/json
      summary: 编辑角色
      tags:
      - 角色管理
  /systemMessage:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页显示多少条
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SystemMessagePage'
      summary: 获取系统公告列表
      tags:
      - 系统公告
    post:
      parameters:
      - description: 系统公告
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.MessageAdd'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 添加系统公告
      tags:
      - 系统公告
  /systemMessage/{id}:
    delete:
      parameters:
      - description: 公告ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      summary: 删除公告
      tags:
      - 系统公告
    put:
      parameters:
      - description: 公告ID
        in: path
        name: id
        required: true
        type: integer
      - description: 公告
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.MessageEdit'
      produces:
      - application/json
      summary: 编辑公告
      tags:
      - 系统公告
swagger: "2.0"
